### ISSUE TITLE
Env. variables are not taken into consideration

### ISSUE THREAD

**Issue by Alek5andr** [webdriverio-community/node-geckodriver#114]
Hello, people!

It seems like offered environment variables are not taken into consideration during an installation of the driver.

For instance, in PowerShell `$env:GECKODRIVER_VERSION="0.30.0"; npm install geckodriver` still installs the latest version.
Same for `$env:GECKODRIVER_FILEPATH="C:/Jenkins/geckodriver-v0.30.0-win64.zip"; npm install geckodriver`.

So what's the point of those variables? Or I'm doing it wrong?

**Comment by christian-bromann** [comment]
We have updated the project which should have fixed the problem. Let me know if it still occurs.
