### ISSUE TITLE
Path attribute returns incorrect bin path

### ISSUE THREAD

**Issue by nickforddev** [webdriverio-community/node-geckodriver#18]
Your docs say to use the binary in /bin/, but the path returned by the module is different, and doesn't lead to anything. I'm basing this expectation on my understanding of how chromedriver works.

For example, if I open up a node process to investigate:

```
> var geckodriver = require('geckodriver');
undefined
> geckodriver
{ path: '/Sites/vue2/node_modules/geckodriver/geckodriver',
  version: '0.14',
  start: [Function],
  stop: [Function] }
```

So when I try to pass `require('geckodriver').path` to Selenium, it can't find the executable.

**Comment by acha5066** [comment]
@nickforddesign I had the same error message as you. It was originally working just using `geckodriver.path` as you describe but I guess my node version changed or something. This is how I resolved it. 

- Made sure I was using the same node version that I originally installed the packages with. 
- Deleted the yarn lock file and re-ran `yarn install` to re-install from package.json from scratch.

After that I could use `geckodriver.path` again. Hopefully that helps.

**Comment by christian-bromann** [comment]
We updated the project and removed the `path` export. If you still think this is a useful export to have please let me know your use case and we can see how we can add it back.
