### ISSUE TITLE
Please don't check Cargo.toml on mozilla-central

### ISSUE THREAD

**Issue by whimboo** [webdriverio-community/node-geckodriver#345]
The code at https://github.com/webdriverio-community/node-geckodriver/blob/61bb32379faa90e28eff5769877e698360f26142/src/constants.ts#L3 checks for some reason the `Cargo.toml` file on mozilla-central. We are not releasing geckodriver from this repository and that file contains information that hasn't been released yet.

Is there a reason why this check is done, and not GitHub is used where we actually release geckodriver from? The URL would be: https://github.com/mozilla/geckodriver/blob/release/Cargo.toml.

I'm asking because we are seeing a huge amount of requests for that file since yesterday, which negatively impacts our performance for tooling.

Thanks.

CC @christian-bromann

**Comment by christian-bromann** [comment]
@whimboo there isn't any particular reason why we pull it from moz central instead of GitHub, this can surely be changed.

**Comment by cgsheeh** [comment]
FYI I think the correct URL to pull from is https://raw.githubusercontent.com/mozilla/geckodriver/release/Cargo.toml, since https://github.com/mozilla/geckodriver/blob/release/Cargo.toml is the Github-UI rendered version.

**Comment by whimboo** [comment]
Oh right. I didn't copy the raw version of the file. Thanks for correcting.



> @whimboo there isn't any particular reason why we pull it from moz central instead of GitHub, this can surely be changed.

That would be great. Thanks.

**Comment by christian-bromann** [comment]
@whimboo thanks!

**Comment by christian-bromann** [comment]
@whimboo @cgsheeh the problem we now discover with the GitHub endpoint is that we get rate limited, can you suggest an alternative?

**Comment by christian-bromann** [comment]
Yeah it seems like these endpoints are static content and not under rate limitation.
