### ISSUE TITLE
a 2.0.4 release for geckodriver with updated tar 

### ISSUE THREAD

**Issue by paimon0715** [webdriverio-community/node-geckodriver#96]
Hi, @vladikoff, I'd like to report a vulnerability introduced by package **tar@6.1.2**:
### Issue Description

   I noticed that a vulnerability is introduced in **_geckodriver@2.0.3_**:
     Vulnerability **SNYK-JS-TAR-1536758** affects package **_tar_** (versions:<4.4.16,>=5.0.0 <5.0.8,>=6.0.0 <6.1.4):  [https://snyk.io/vuln/SNYK-JS-TAR-1536758](https://snyk.io/vuln/SNYK-JS-TAR-1536758)
  The above vulnerable package is referenced by **_geckodriver@2.0.3_** via:
`geckodriver@2.0.3 ➔ tar@6.1.2`

Since **_geckodriver@2.0.3_** ([6,876 downloads per week](https://www.npmjs.com/package/geckodriver/v/2.0.3?activeTab=versions)) is referenced by **166** downstream projects (e.g., [@bigtest/server 0.24.2](https://www.npmjs.com/package/@bigtest/server) (latest version), [@bigtest/cli 0.19.0](https://www.npmjs.com/package/@bigtest/cli) (latest version), [@bigtest/webdriver 0.8.4](https://www.npmjs.com/package/@bigtest/webdriver) (latest version), [bigtest 0.14.3](https://www.npmjs.com/package/bigtest) (latest version), [@justindiveshanchetty/automation_framework 1.0.27](https://www.npmjs.com/package/@justindiveshanchetty/automation_framework) (latest version)), the vulnerability [**SNYK-JS-TAR-1536758**](https://snyk.io/vuln/SNYK-JS-TAR-1536758) can be propagated into these downstream projects and expose security threats to them via the following package dependency paths:
 (1)`@bigtest/cli@0.19.0 ➔ @bigtest/server@0.24.2 ➔ @bigtest/webdriver@0.8.4 ➔ geckodriver@2.0.3 ➔ tar@6.1.2`
(2)`@faltest/cli@4.0.0 ➔ @faltest/remote@6.0.4 ➔ geckodriver@2.0.3 ➔ tar@6.1.2`
  **......**

If **_geckodriver@2.0.\*_** removes the vulnerable package from the above version, then its fixed version can help downstream users decrease their pain.

**Given the large number of downstream users, could you help update your package to remove the vulnerability from geckodriver@2.0.3 ?**

### Fixing suggestions

In **_geckodriver@2.0.4_**, maybe you can kindly try to perform the following upgrade(**not crossing major version**) :
`tar 6.1.2 ➔ 6.1.4`; 

**Note:**
_**tar@6.1.4**(>=6.1.4) has fixed the vulnerability [**SNYK-JS-TAR-1536758**](https://snyk.io/vuln/SNYK-JS-TAR-1536758)._

Thank you for your attention to this issue and welcome to share other ways to resolve the issue.^_^

**Comment by st-schaefer** [comment]
Please upgrade tar to **>=6.1.9** according to this advisory: https://www.npmjs.com/advisories/1781

**Comment by christian-bromann** [comment]
fixed in #115
