### ISSUE TITLE
postinstall step doesn't use cafile from npmrc

### ISSUE THREAD

**Issue by Stift** [webdriverio-community/node-geckodriver#98]
When we try to download the Geckodriver from a local CDN, we have a custom certificate on that CDN. Unfortunately the cafile (https://docs.npmjs.com/cli/v6/using-npm/config#cafile) setting from npmrc is not checked and used while downloading.

**Comment by christian-bromann** [comment]
We have updated the way this package downloads the Geckodriver. If the issue still persist please let me know.
